apiVersion: v1
kind: LimitRange
metadata:
  name: storage-limit-range
  namespace: default
spec:
  limits:
    - default:
        ephemeral-storage: "300Mi"
      type: Container
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: pod-api
      labels:
        app: api
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
        - name: api-container
          image: ghcr.io/soat-fiap/fiap.techchallenge.bytemeburger/api:sha-b83177c
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
              - ALL
          ports:
            - name: liveness-port
              containerPort: 8080
            - containerPort: 80
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              port: liveness-port
              path: /healthz
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 20
          readinessProbe:
            httpGet:
              port: liveness-port
              path: /healthz
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: 50m
          env:
            - name: MySqlSettings__Password
              valueFrom:
                secretKeyRef:
                  name: secret-db
                  key: MYSQL_PASSWORD
            - name: MySqlSettings__UserId
              valueFrom:
                secretKeyRef:
                  name: secret-db
                  key: MYSQL_USER
          envFrom:
            - configMapRef:
                name: configmap-api
            - secretRef:
                name: secret-mercadopago
